### ISSUE TITLE
Add extra condition that checks if the current score is better than the already saved score

### ISSUE THREAD

**Issue by NilesHusk** [Wopsie/DonDiabloPvB#1]
It is a good idea to add an extra condition to the UpdateProgress function in the progress.cs script.
`void UpdateProgress(string name,int score) {
        PlayerPrefs.SetInt(name, score);
    }`
This is important because then the high score wont be overwritten

**Comment by Wopsie** [comment]
@koedijk Has this been added yet?

**Comment by koedijk** [comment]
Added a statement that score will only be saved when its higher than previous score.
